add check code to ensure proceed only if succeed

diff --git a/server/tmux/build_tmux b/server/tmux/build_tmux
--- a/server/tmux/build_tmux
+++ b/server/tmux/build_tmux
@@ -1,3 +1,11 @@
+check(){
+if [ $? = 1 ]; then
+echo "failed";
+exit
+fi
+}
+
+
 build_tmux_func(){
 if [ -z $1 ];then
 echo "input install path"
@@ -18,10 +26,15 @@ cd libevent
 make
 make install
 
+check()
+
 echo "build tmux"
 cd $buildPath/tmux
 ./autogen.sh
 ./configure CFLAGS=-I$1/include LDFLAGS=-L$1/lib --prefix=$1
+
+check()
+
 make
 make install
 if [ $? = 0 ];then
